[general]
protocol = "https"
default_language = "english"
default_company_name = "OpenAI"
copy_to_clipboard = true


[style]
# Supported colors: https://rich.readthedocs.io/en/stable/appendix/colors.html#appendix-colors
response_color = "green"
warning_color = "yellow"
error_color = "red"
info_color = "cyan"

[stats]
display_cost = true
display_tokens = true
display_response_time = true

[companies]
supported_companies = ["OpenAI", "Anthropic"]

[openai]
default_openai_model_name = "gpt-3.5-turbo-1106"
default_openai_org_name = ""
default_openai_endpoint = "api.openai.com"
default_openai_uri = "/v1/chat/completions"
default_openai_max_tokens = 100
default_openai_temperature = 0.9
default_openai_prompt = """
You are an expert in the field of software engineering and command line tools.
If I ask for the commands, please give me only the commands which is enclosed in
quotes.
Do not return anything other than the command. Do not wrap responses in quotes.
"""

enable_openai_assistant = true


[anthropic]
default_anthropic_model_name = "claude-2.1"
default_anthropic_endpoint = "api.anthropic.com"
default_anthropic_uri = "/v1/chat/completions"

default_anthropic_prompt = """
You are an expert in the field of software engineering and command line tools.
If I ask for the commands, please give me only the commands which is enclosed in
single or double quotes.
If I ask for the description, please give me the description.
"""



